修復subcontent消失問題，修改button邏輯
010tech/gatsby-client-rounded-template pull request #10
Opened 2022-05-06 05:59 UTC by VG88580928

修復subcontent消失問題， 當畫面小於 sm,則將 button 移到下方防止跑版

2022-05-06 06:32 UTC, imgarylai requested changes

2022-05-06 06:32 UTC, imgarylai commented on src/components/layout.jsx
> +        <Navbar mainUrl={mainUrl} cta={cta} logo={logo} />
Can we just call `useSetting` hook in the Navbar component?

2022-05-06 06:32 UTC, imgarylai commented on src/components/navbar.jsx
> -  const { mainUrl, cta, logo } = useSetting()
This old way is alright. This is how hooks work.

2022-05-06 06:32 UTC, imgarylai commented on src/components/post/Content.jsx
> +  }
This can be something like `{A ? A : B ? B : ""}`. If nothing in markdown, it is just an empty div in the HTML.

2022-05-06 06:41 UTC, crzbread commented
列出的問題 都先在[澤康](https://github.com/010tech/blog.homehnh.com.tw)這邊處理完後再回來改吧

2022-05-06 06:41 UTC, VG88580928 commented on src/components/layout.jsx
> +        <Navbar mainUrl={mainUrl} cta={cta} logo={logo} />
如果我只在 Navbar `呼叫 useSetting`，那手機版右下角那顆按鈕會需要再一次在 layout 呼叫 `useSetting` 來取得 cta 資訊，會多呼叫一次，不知道有沒有關係

2022-05-14 00:44 UTC, imgarylai approved these changes

2022-05-16 02:26 UTC, crzbread approved these changes

2022-05-16 02:27 UTC, merged