refactor: 重構命名方式、新增判斷 gtm click classes
010tech/gatsby-client-rounded-template pull request #20
Opened 2022-09-05 07:52 UTC by allenzx0202

- 命名規則不統一
- config 中 favicon 命名
- contentful CTA model 中新增自訂義 class 的欄位 (for gtm click classes)，程式需判斷有無填寫此欄位

2022-09-05 08:35 UTC, stanley-yin requested changes

2022-09-05 08:35 UTC, stanley-yin commented on src/components/PoweredLink.jsx
> +    "Welly Seo"
SEO?

2022-09-07 01:13 UTC, crzbread approved these changes

2022-09-07 09:53 UTC, stanley-yin approved these changes

2022-10-06 08:40 UTC, merged